"""initial_squash

Revision ID: 750c817a87b8
Revises: 
Create Date: 2026-06-21 16:30:06.471879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '750c817a87b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('stock', 'etf', 'fund', 'crypto', 'other', name='asset_kind'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'name', name='assets_symbol_name_key')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('profiles',
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.Enum('moderate', 'agressive', 'conservative', name='risk_profile_kind'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('clerk_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('trigger_field', sa.String(), nullable=False),
    sa.Column('trigger_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('asset_daily_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('absolute_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='asset_daily_metrics_asset_id_date_key')
    )
    op.create_table('asset_monthly_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='asset_monthly_metrics_asset_id_date_key')
    )
    op.create_table('asset_prices',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'date'),
    sa.UniqueConstraint('asset_id', 'date', name='asset_prices_asset_id_date_key')
    )
    op.create_index('ix_asset_price_asset_date_desc', 'asset_prices', ['asset_id', 'date'], unique=False)
    op.create_table('portfolio_daily_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pnl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_drawdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('volatility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_portfolio_daily_metrics_user_date')
    )
    op.create_table('portfolio_monthly_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('twr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('var', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_portfolio_monthly_metrics_user_date')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_invested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unrealized_pnl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('realized_pnl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakdown_by_currency', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakdown_by_account', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pnl_percentage_account_daily', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('pnl_percentage_asset_daily', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_drawdown_portfolio_daily', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_drawdown_account_daily', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('asset_weight_weekly', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('currency_exposure_weekly', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('account_daily_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_monthly_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('twr', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('dietz', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('var', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sortino', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('assets_correlation', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividend_account_date', 'dividends', ['account_id', 'date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_dividends', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('buy', 'sell', 'dividend', 'fee', 'deposit', 'withdrawal', name='transaction_kind'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_account_executed', 'transactions', ['account_id', 'executed_at'], unique=False)
    op.create_table('position_daily_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_daily_metrics')
    op.drop_index('ix_transaction_account_executed', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('positions')
    op.drop_index('ix_dividend_account_date', table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('account_monthly_metrics')
    op.drop_table('account_daily_metrics')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('portfolio_monthly_metrics')
    op.drop_table('portfolio_daily_metrics')
    op.drop_index('ix_asset_price_asset_date_desc', table_name='asset_prices')
    op.drop_table('asset_prices')
    op.drop_table('asset_monthly_metrics')
    op.drop_table('asset_daily_metrics')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
