"""add alerts table/columns

Revision ID: 7abe19b6030f
Revises: cf8cadfbbaeb
Create Date: 2026-06-14 03:56:37.406642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7abe19b6030f'
down_revision: Union[str, Sequence[str], None] = 'cf8cadfbbaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('alerts')
    op.drop_constraint(op.f('asset_daily_metrics_unique'), 'asset_daily_metrics', type_='unique')
    # Fix NULL values in currency before making it NOT NULL
    op.execute("UPDATE asset_prices SET currency = 'USD' WHERE currency IS NULL")
    op.alter_column('asset_prices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('assets', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.drop_constraint(op.f('assets_symbol_name_unique'), 'assets', type_='unique')
    #op.add_column('portfolio_daily_metrics', sa.Column('portfolio_id', sa.UUID(), nullable=False))
    #op.drop_constraint(op.f('portfolio_daily_user_id_fk'), 'portfolio_daily_metrics', type_='foreignkey')
    #op.create_foreign_key(None, 'portfolio_daily_metrics', 'portfolio_snapshots', ['portfolio_id'], ['id'], ondelete='CASCADE')
    #op.drop_column('portfolio_daily_metrics', 'user_id')
    #op.add_column('portfolio_monthly_metrics', sa.Column('portfolio_id', sa.UUID(), nullable=False))
    #op.drop_constraint(op.f('portfolio_monthly_user_id_fk'), 'portfolio_monthly_metrics', type_='foreignkey')
    #op.create_foreign_key(None, 'portfolio_monthly_metrics', 'portfolio_snapshots', ['portfolio_id'], ['id'], ondelete='CASCADE')
    #op.drop_column('portfolio_monthly_metrics', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_monthly_metrics', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolio_monthly_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_monthly_user_id_fk'), 'portfolio_monthly_metrics', 'profiles', ['user_id'], ['clerk_id'])
    op.drop_column('portfolio_monthly_metrics', 'portfolio_id')
    op.add_column('portfolio_daily_metrics', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolio_daily_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_daily_user_id_fk'), 'portfolio_daily_metrics', 'profiles', ['user_id'], ['clerk_id'])
    op.drop_column('portfolio_daily_metrics', 'portfolio_id')
    op.create_unique_constraint(op.f('assets_symbol_name_unique'), 'assets', ['symbol', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('assets', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('asset_prices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.create_unique_constraint(op.f('asset_daily_metrics_unique'), 'asset_daily_metrics', ['asset_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('Portfolio', 'Asset', 'Account', 'Position', name='alert_kind'), autoincrement=False, nullable=False),
    sa.Column('trigger_field', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trigger_value', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], name=op.f('alert_user_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    # ### end Alembic commands ###
