"""add unique constraints to assets, asset_metrics, asset_prices

Revision ID: 8a9932449e9f
Revises: c6c34ff6f9f0
Create Date: 2026-06-14 18:03:31.651382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9932449e9f'
down_revision: Union[str, Sequence[str], None] = 'c6c34ff6f9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('asset_daily_metrics_asset_id_date_key', 'asset_daily_metrics', ['asset_id', 'date'])
    op.create_unique_constraint('asset_monthly_metrics_asset_id_date_key', 'asset_monthly_metrics', ['asset_id', 'date'])
    op.create_unique_constraint('asset_prices_asset_id_date_key', 'asset_prices', ['asset_id', 'date'])
    op.create_unique_constraint('assets_symbol_name_key', 'assets', ['symbol', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_symbol_name_key', 'assets', type_='unique')
    op.drop_constraint('asset_prices_asset_id_date_key', 'asset_prices', type_='unique')
    op.drop_constraint('asset_monthly_metrics_asset_id_date_key', 'asset_monthly_metrics', type_='unique')
    op.drop_constraint('asset_daily_metrics_asset_id_date_key', 'asset_daily_metrics', type_='unique')
    # ### end Alembic commands ###
