"""fix alerts table schema

Revision ID: c6c34ff6f9f0
Revises: 7abe19b6030f
Create Date: 2026-06-14 09:05:46.719072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6c34ff6f9f0'
down_revision: Union[str, Sequence[str], None] = '7abe19b6030f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'notified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('alerts', 'last_triggered',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_alerts_notified_at'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_user_active_type'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_user_id'), table_name='alerts')
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_alerts_user'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'profiles', ['user_id'], ['clerk_id'])
    op.drop_constraint(op.f('asset_monthly_metrics_unique'), 'asset_monthly_metrics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('asset_monthly_metrics_unique'), 'asset_monthly_metrics', ['asset_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_alerts_user'), 'alerts', 'profiles', ['user_id'], ['clerk_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.create_index(op.f('idx_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index(op.f('idx_alerts_user_active_type'), 'alerts', ['user_id', 'is_active', 'type'], unique=False)
    op.create_index(op.f('idx_alerts_notified_at'), 'alerts', ['notified_at'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'last_triggered',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('alerts', 'notified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
