"""sincronizar modelos

Revision ID: d807af665233
Revises: cf8cadfbbaeb
Create Date: 2026-05-25 20:39:33.176429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd807af665233'
down_revision: Union[str, Sequence[str], None] = 'cf8cadfbbaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('stock', 'etf', 'fund', 'crypto', 'other', name='asset_kind'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_symbol'), 'asset', ['symbol'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('asset_price',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'date')
    )
    op.create_index('ix_asset_price_asset_date_desc', 'asset_price', ['asset_id', 'date'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('buy', 'sell', 'dividend', 'fee', 'deposit', 'withdrawal', name='transaction_kind'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_account_executed', 'transaction', ['account_id', 'executed_at'], unique=False)
    op.drop_table('asset_monthly_metrics')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_transaction_account_executed'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('position_daily_metrics')
    op.drop_table('positions')
    op.drop_table('asset_daily_metrics')
    op.drop_table('portfolio_daily_metrics')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_price_asset_date_desc'), table_name='asset_prices')
    op.drop_table('asset_prices')
    op.drop_index(op.f('ix_dividend_account_date'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('portfolio_monthly_metrics')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('account_monthly_metrics')
    op.drop_table('account_daily_metrics')
    op.create_index(op.f('ix_profiles_clerk_id'), 'profiles', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_clerk_id'), table_name='profiles')
    op.create_table('account_daily_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('volatility', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('account_daily_metrics_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_daily_metrics_pkey'))
    )
    op.create_table('account_monthly_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('twr', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('dietz', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
    sa.Column('var', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('sortino', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
    sa.Column('assets_correlation', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('account_monthly_metrics_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_monthly_metrics_pkey'))
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_value', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('total_invested', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('realized_pnl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('breakdown_by_currency', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('breakdown_by_account', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], name=op.f('portfolio_snapshots_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_snapshots_pkey'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('broker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], name=op.f('accounts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('portfolio_monthly_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('twr', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('dietz', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('var', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('accounts_correlation', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_snapshots.id'], name=op.f('portfolio_monthly_metrics_portfolio_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_monthly_metrics_pkey'))
    )
    op.create_table('dividends',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('net_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('dividends_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('dividends_asset_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('dividends_pkey'))
    )
    op.create_index(op.f('ix_dividend_account_date'), 'dividends', ['account_id', 'date'], unique=False)
    op.create_table('asset_prices',
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_prices_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'date', name=op.f('asset_prices_pkey'))
    )
    op.create_index(op.f('ix_asset_price_asset_date_desc'), 'asset_prices', ['asset_id', 'date'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kind', postgresql.ENUM('stock', 'etf', 'fund', 'crypto', 'other', name='asset_kind'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('portfolio_daily_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('volatility', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('fx_decomposition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_snapshots.id'], name=op.f('portfolio_daily_metrics_portfolio_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_daily_metrics_pkey'))
    )
    op.create_table('asset_daily_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('absolute_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('volatility', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_daily_metrics_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_daily_metrics_pkey'))
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('avg_cost', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('realized_pnl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('total_dividends', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('total_fees', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('last_transaction_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('positions_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('positions_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('positions_pkey'))
    )
    op.create_table('position_daily_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('personal_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('position_daily_metrics_position_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('position_daily_metrics_pkey'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kind', postgresql.ENUM('buy', 'sell', 'dividend', 'fee', 'deposit', 'withdrawal', name='transaction_kind'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('fee', sa.NUMERIC(precision=20, scale=8), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('transactions_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('transactions_asset_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transaction_account_executed'), 'transactions', ['account_id', 'executed_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pnl_percentage_account_daily', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('pnl_percentage_asset_daily', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('max_drawdown_portfolio_daily', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('max_drawdown_account_daily', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('asset_weight_weekly', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('currency_exposure_weekly', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.clerk_id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('asset_monthly_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('beta', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_monthly_metrics_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_monthly_metrics_pkey'))
    )
    op.drop_index('ix_transaction_account_executed', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('ix_asset_price_asset_date_desc', table_name='asset_price')
    op.drop_table('asset_price')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_asset_symbol'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
