"""check_drift_temporal

Revision ID: e72240769824
Revises: 438b0eb14291
Create Date: 2026-06-21 01:27:30.369206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72240769824'
down_revision: Union[str, Sequence[str], None] = '438b0eb14291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_daily_metrics', sa.Column('portfolio_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_portfolio_daily_metrics_user_date'), 'portfolio_daily_metrics', type_='unique')
    op.drop_constraint(op.f('pdm_user_id_fk'), 'portfolio_daily_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_daily_metrics', 'portfolio_snapshots', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.add_column('portfolio_monthly_metrics', sa.Column('portfolio_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_portfolio_monthly_metrics_user_date'), 'portfolio_monthly_metrics', type_='unique')
    op.drop_constraint(op.f('pmm_user_id_fk'), 'portfolio_monthly_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_monthly_metrics', 'portfolio_snapshots', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_column('portfolio_monthly_metrics', 'user_id')
    op.add_column('position_daily_metrics', sa.Column('personal_return', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_daily_metrics', 'personal_return')
    op.add_column('portfolio_monthly_metrics', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolio_monthly_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('pmm_user_id_fk'), 'portfolio_monthly_metrics', 'profiles', ['user_id'], ['clerk_id'])
    op.create_unique_constraint(op.f('uq_portfolio_monthly_metrics_user_date'), 'portfolio_monthly_metrics', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('portfolio_monthly_metrics', 'portfolio_id')
    op.drop_constraint(None, 'portfolio_daily_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('pdm_user_id_fk'), 'portfolio_daily_metrics', 'profiles', ['user_id'], ['clerk_id'])
    op.create_unique_constraint(op.f('uq_portfolio_daily_metrics_user_date'), 'portfolio_daily_metrics', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('portfolio_daily_metrics', 'portfolio_id')
    # ### end Alembic commands ###
