name: Sync Funds New


on:
  # push:
  #    branches:
  #      - test/gh_actions_new_db #solo para testeo
  schedule:
    - cron: "0 5 * * *"  # todos los días en la noche
  workflow_dispatch:      

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: pip install requests psycopg2-binary pandas

      - name: Correr script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: python sync_funds_new.py