name: Users Warnings


on:
  push:
    branches:
      - feat/asset-metrics-monthly-and-mailer #solo para testeo
  schedule:
      - cron: "0 10 * * *"  
  workflow_dispatch:      

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Correr script
        env:
          DATABASE_URL:  ${{ secrets.DATABASE_URL_ASYNC }}
        run: python scripts_ghactions/warnings_users.py